#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: Merge-1907-upstream

on:
  schedule:
    - cron: 30 19 */6 * *
  # push:
  #   branches: 
  #     - main
     # 点击star才会触发    
  watch:
      types: [started]

jobs:

  merge:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: 1
        fetch-depth: 0
        lfs: true

    - name: Set git identity
      run : |
       git config --global user.email "lede-project@foxmail.com"
        git config --global user.name "lede-project"
        
    - name: Load upstream commits
      run: git pull https://github.com/52014app/luci-app-godproxy.git --log --no-commit

    - name: Apply commit changes
      run: |
        if [ -f ./.git/MERGE_MSG ]; then
        mkdir ./tmp && cp ./.git/MERGE_MSG ./tmp/message
        sed -i "1c [bot] AutoMerging: merge all upstream's changes:" ./tmp/message
        sed -i '/^\#.*/d' ./tmp/message
        git commit --file="./tmp/message"
        else
        echo "There is no merge commits."
        fi    
        
    - name: Push Commits
      env:
        DOWNSTREAM_BRANCH: 1
      run: git push origin $DOWNSTREAM_BRANCH
      
    - name: Delete workflow runs
      uses: small-5/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 1
